### ISSUE TITLE
Populate `minimumHeightAboveSurfaceInMeters` from different fields

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#14]
Comment by @sarahcd:

> `gps."height-above-ellipsoid" AS minimumDistanceAboveSurfaceInMeters`
> Some datasets have 'height-above-ellipsoid'. The datum is different but both fit the definition of minimumDistanceAboveSurfaceInMeters. 
> Is it possible to map conditionally depending on which attribute is present?
> Rarely, both attributes are present. And there is also 'height-raw', but this does not define units so should be ignored.

**Comment by sarahcd** [comment]
These are the 2 possibilities.
`gps."height-above-ellipsoid" AS minimumDistanceAboveSurfaceInMeters`
`gps."height-above-msl" AS minimumDistanceAboveSurfaceInMeters`
You could just include these both in the code and it would map whichever is available. I could run it with an example containing both fields and see if/what problems it causes (this would be uncommon).

**Comment by peterdesmet** [comment]
Do you have such an example?

**Comment by peterdesmet** [comment]
And which field should take preference?

**Comment by sarahcd** [comment]
I think it makes sense to take gps."height-above-ellipsoid" first, this one is more common. I'll send you an example.

**Comment by peterdesmet** [comment]
I sent a sample file by email, can you verify and close this issue if ok?

**Comment by peterdesmet** [comment]
Verified and ok
