### ISSUE TITLE
Sampling protocol

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#26]
@sarahcd what sampling protocol to use:

- [x] Deployment start: `tag deployment start`?
- [x] GPS positions: `gps` or `gps sensor`?
- [x] Deployment end: `tag deployment end`?

**Comment by sarahcd** [comment]
I think samplingProtocol='gps' + basisOfRecord='MachineObservation' is good for GPS positions, unless there is any other precedent or reason from GBIF's side to further clarify as 'gps sensor'. For deployment ends, see my comment here https://github.com/inbo/movepub/issues/10#issuecomment-1131669787

**Comment by peterdesmet** [comment]
Updated to `tag attachment` in a68d6d2. For the identifiers, I still used `_start`

samplingProtocol | parentEventID | eventID | occurrenceID
--- | --- | --- | ---
tag attachment | 5515851_5642 | 5515851_5642_start | 5515851_5642_start
gps | 5515851_5642 | 20432407608 | 20432407608
gps | 5515851_5642 | 20432407611 | 20432407611

@sarahcd can you confirm this is ok?
