### ISSUE TITLE
Records outside of deployment

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#27]
@sarahcd, in 2017 you [remarked](https://github.com/peterdesmet/movebank2gbif/issues/9):

> Published datasets in Movebank often include records (rows in the data file) that do not represent a location where an animal was observed:
> 
> Pre- or post-deployment records. For these 'individual-local-identifier' is blank. This will only occur rarely; I think none so far include them but we have a dataset in review with data from some undeployed test tags.

I assume all published datasets exclude points outside a deployment? Or should we filter on those in the SQL?

**Comment by sarahcd** [comment]
As mentioned in that note, there are 1 or 2 published datasets where undeployed calibration data are an important part of the reported analysis and are included in the published data. These records will have no associated taxon or animal identifier. This is not common, but ideally the script will ignore these records, either through filtering or by ensuring those records are ignored at some other stage in the processing.

**Comment by peterdesmet** [comment]
Script now excludes GPS records that have no associated animal-taxon.
