### ISSUE TITLE
Add alternative labels for `magnetic field raw x` and alike

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#28]
Provide alternative labels for (official first, alternative second):

- [x] `magnetic field raw x`:`mag magnetic field raw x`
- [x] `magnetic field raw y`: `mag magnetic field raw y`
- [x] `magnetic field raw z`: `mag magnetic field raw z`
- [x] `light level`: `gls light level`
- [x] `Ornitela transmission protocol`: `orn transmission protocol`
- [x] ~`study time zone`~: `study timezone` is now the official term http://vocab.nerc.ac.uk/collection/MVB/current/MVB000177/
- [x] ~`local timestamp`~: `study local timestamp` is not the official term http://vocab.nerc.ac.uk/collection/MVB/current/MVB000140/

Original comment:

These fields are only defined without the `mag` part in the Movebank attribute dictionary (http://vocab.nerc.ac.uk/collection/MVB/current/MVB000151/), in contrast with e.g.

- `gps:hdop`: http://vocab.nerc.ac.uk/collection/MVB/current/MVB000118/
- `eobs:key-bin-checksum`: http://vocab.nerc.ac.uk/collection/MVB/current/MVB000095/
- `bar:barometric-pressure`: http://vocab.nerc.ac.uk/collection/MVB/current/MVB000055/ (alt label)

**Comment by peterdesmet** [comment]
Same for `gls:light level`

**Comment by peterdesmet** [comment]
Same for `orn transmission protocol`

**Comment by sarahcd** [comment]
Thanks Peter. I have a way of filtering to find all these and add the alt names for the next vocab update, so no need to send each one you find. :)

**Comment by peterdesmet** [comment]
Ok! It's also a reminder for myself, since I'm adding code to fix it in the meantime. Let me know when a new version is up.

**Comment by sarahcd** [comment]
Confirming these inconsistencies should all be resolved once I update the NERC vocabulary next. In preparation....

**Comment by peterdesmet** [comment]
The custom replacements in `get_mvb_term()` to deal with the missing labels can now all be removed thanks to MVB version 4! 👏

**Comment by sarahcd** [comment]
great :)
