### ISSUE TITLE
Very precise coordinateUncertaintyInMeters

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#31]
Reviewer of the data:

> Please consider recalculating or re-estimating the entries in the coordinateUncertaintyInMeters field. I would have
expected that a default uncertainty could be provided for a GPS tracking unit (or a handheld GPS). Instead, the entries
are hugely varied and given to 0.1 m, which (again) is unbelievable.

My answer:

> Values in this field are based on what is recorded as horizontal precision by the GPS tracker. These records can show outliers. We prefer to provide the raw value (as available in the source record), rather than setting a cut-off (e.g. the default 30m as lower value for GPS).

@sarahcd @tucotuco what would you suggest?

**Comment by tucotuco** [comment]
Definitely do not mess with raw data. The GPS tracking units give a theoretical value of the uncertainty of the measurement under the actual conditions. The recommended default values are for when the device "accuracy" is not recorded. See [GPS Accuracy](https://docs.gbif.org/georeferencing-best-practices/1.0/en/#gps-accuracy) in Georeferencing Best Practices.

**Comment by peterdesmet** [comment]
Ok, I will leave the horizontal accuracy as measured by the GPS unit as is in `coordinateUncertaintyInMeters`.

**Comment by sarahcd** [comment]
agree with @tucotuco
