### ISSUE TITLE
Empty fields

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#34]
Reviewer of data:

> The organismName and reproductiveCondition fields are empty and should be deleted.

My answer:

> We developed a standardized approach for transforming data from a Movebank study to Darwin Core data (https://inbo.github.io/movepub/reference/write_dwc.html). This approach includes providing fields that might not be available/populated in the source data, such as organismName and reproductiveCondition. We could check and remove empty fields manually for each dataset, but we prefer to use the same (automated) approach for all datasets.

@sarahcd @tucotuco what would you suggest?

**Comment by tucotuco** [comment]
I suggest keeping the schema constant. There is nothing wrong with fields be left empty when there are no data, but showing there is a place for them has value.

**Comment by sarahcd** [comment]
I'm not sure the implications from the GBIF side. Keeping a consistent approach for all the Movebank datasets is both easier and maybe provides an advantage for GBIF users: when checking across the Movebank studies in GBIF, the empty columns indicate that this information is indeed not present in the given dataset (if missing, it could mean that it was present in Movebank but excluded in GBIF).
