### ISSUE TITLE
Add `study_id` parameter to `write_dwc()`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#35]
Indeed, the study URL is pulled from the second `alternativeIdentifier` in the EML:

https://github.com/inbo/movepub/blob/d9f1a2d0689cdc9b902a656c0333f83a893aa3e7/R/write_dwc.R#L96

To allow users to define it, we could:

- Add a parameter `study_id` (from which the link can be build)
- Have users correct add this when they edit metadata in the IPT

Given that the link is used in the description _and_ as external link, I think a parameter would be good?

_Originally posted by @peterdesmet in https://github.com/inbo/movepub/issues/25#issuecomment-1222276108_

**Comment by peterdesmet** [comment]
@sarahcd Is it easier to people to ask for the study_id (`1605797471`) or study_url (`https://www.movebank.org/cms/webapp?gwt_fragment=page=studies,path=study1605797471`). The former is an official MVB term, the latter can be copied from the browser.

**Comment by sarahcd** [comment]
I think the study_ID is fine. People have independently gotten used to using the study ID to refer to their studies, so anyone using this package should not have a problem finding it.

**Comment by peterdesmet** [comment]
This is now implemented. @sarahcd can you install the package again and see if it works on your end?

**Comment by sarahcd** [comment]
It works!
