### ISSUE TITLE
Update message when loading

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#37]
@sarahcd in https://github.com/inbo/movepub/pull/36#issue-1358998067:

> ... One additional request is for the messages shown as the code is executed. Where messages say 'Please make sure you have the right to access data....', please somewhere refer to 'Movebank’s terms of use at https://www.movebank.org/cms/movebank-content/general-movebank-terms-of-use'. If you point me to the file/s with the message text I can suggest it there directly.

**Comment by peterdesmet** [comment]
The message is:

> Please make sure you have the right to access data from this Data Package for your intended use.
> Follow applicable norms or requirements to credit the dataset and its authors.
> For more information, see https://doi.org/10.5281/zenodo.5653311

@sarahcd it is a standardized message provided by `frictionless::read_package()`. Since it is not part of movepub, it cannot be customized, unless we create a separate read function in movepub, which I don't think we should do.

**Comment by sarahcd** [comment]
Understood, no need to make a separate function.
