### ISSUE TITLE
Write orcids as https

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#41]
Update http to https in:

https://github.com/inbo/movepub/blob/afffbded7b9bf2287fdeddb985d3583a58b03e94/R/write_dwc.R#L146

Once https://github.com/gbif/ipt/issues/1819 is included in the next version of the IPT.

**Comment by PietrH** [comment]
Does
https://github.com/inbo/movepub/blob/main/R/datacite_to_eml.R#L37
also need to be changed? 

```R
      list(
        directory = "http://orcid.org/",
        gsub("https://orcid.org/", "", .$nameIdentifiers[[1]]$nameIdentifier)
      )
```

**Comment by peterdesmet** [comment]
Yes.
