### ISSUE TITLE
Include `scientificNameID` to make datasets valid for OBIS

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#43]
This would require a call to WoRMS, with the `worrms` package. I see no function to get the LSID directly, so it would be something like:

```R
aphia_id <- worrms::wm_name2id(name = "Larus fuscus")
scientific_name_id <- paste("urn:lsid:marinespecies.org:taxname", aphia_id, sep = ":") # but keep empty if aphia_id is empty
```

**Comment by rubenpp7** [comment]
Maybe this could be interesting as well https://github.com/iobis/obistools/blob/master/R/match_taxa.R . It also accounts for non exact matches

**Comment by peterdesmet** [comment]
## Approach 1

Extract unique taxa (vector) from reference data, run it through worrms and convert back to a dataframe, which can then be loaded as sqlite table and `LEFT JOIN`ed

```R
taxa_vector <- dplyr::distinct(ref, `animal-taxon`) %>% dplyr::pull()
taxa <-
  taxa_vector %>%
  worrms::wm_name2id_() %>%
  dplyr::as_tibble() %>%
  tidyr::pivot_longer(cols = dplyr::everything()) %>%
  dplyr::rename(scientific_name = name, aphia_id = value)
```

## Approach 2

Run a rowwise mutate directly on the reference data:

```
ref %>% rowwise() %>% mutate(aphia_id = worrms::wm_name2id(`animal-taxon`))
```

This is slower, since it the function is called for every record (typically less than 100). But avoids the tidyr dependency and loading in database. It will also return an error on no match.
