### ISSUE TITLE
Movebank study ids are not 32 bit integers

### ISSUE THREAD

**Issue by SWotherspoon** [inbo/movepub#44]
In write_dwc there is an assertion

```
assertthat::assert_that(
    !is.na(as.integer(study_id)),
    msg = glue::glue("`study_id` ({study_id}) must be an integer.")
  )
```

This is an error because movebank study ids are not necessarily 32 bit integers, eg

https://www.movebank.org/cms/webapp?gwt_fragment=page=studies,path=study2391441038

but 2391441038 is not a 32 bit integer.

Could possibly replace with 

```
assertthat::assert_that(
    regexpr("^\\d+$",as.character(study_id))==1,
    msg = glue::glue("`study_id` ({study_id}) must be an integer.")
  )
```

**Comment by peterdesmet** [comment]
Thanks! Excellent catch. Now resolved in 4878419. You can try it out by reinstalling the package.
