### ISSUE TITLE
Write tests for `write_dwc()`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#46]
Similar to camtraptor, this package could benefit from snapshot tests for `write_dwc()`. In contrast with camtraptor, `write_dwc()` writes both an `eml.xml` and `dwc_occurrence.csv` file. And there is no example dataset included in the package. You can use this dataset though:

```
o_assen <-
  frictionless::read_package("https://zenodo.org/record/5653311/files/datapackage.json") %>%
  # Remove the large acceleration resource we won't use (and thus won't download)
  frictionless::remove_resource("acceleration") %>%
  frictionless::write_package()
```

It can potentially be reduced to fewer animals.

- [ ] Write helper function to download example dataset (so it can be used locally)
  - [ ] Potentially reduce `reference-data` and `gps` data to a set of 3-4 animal-ids to reduce size
  - [ ] Downloaded files should be removed after tests
  - [ ] If the function is called directly from tests (rather assigned to a variable at the beginning of the tests), it should check if the local files are available?
- [x] Test expected Darwin Core mapping
- [x] Test expected EML file (note that there is a UUID that is expected to change)

@pietrH would you be willing to tackle this?

**Comment by PietrH** [comment]
Sure! Some questions:

1. Could we include a reduced version of `o_assen` as an example in the package? This way we could run the tests without internet access while also speeding things up. I don't think it would need to be very big for the snapshots to work. Are there any other plans to add an example dataset in `movepub`?

1. Do I understand correctly you want to compare the `write_dwc()` output to a reference version (expectation) of `eml.xml` and `dwc_occurrence.csv` which are included in the package? In this case it's in our best interest to keep both the test output and the expectation as small as possible. Both for speed, and so it's easy to find what's changed if the snapshot fails.

1. I notice you use SQLite for the darwincore mapping, we just moved away from this for `camtraptor`. Is this something you would consider for `movepub` (in a later stage) ?

**Comment by peterdesmet** [comment]
1. Sure, including a local example dataset makes sense
2. Correct.
3. Yes, something to consider indeed (at a later stage)

**Comment by PietrH** [comment]
So, we'll be including a reference dataset built from zenodo. Documented in `R/data.R ` similarly to `camtraptor`: [reference](https://github.com/inbo/camtraptor/blob/f3bd01da581bae6ea8c9a9de64bf65f234549f2f/R/data.R)

It should contain at least 3 bird species, one of which has no records.
