### ISSUE TITLE
Terms like `deploy-on measurements` written with hyphen in NERC

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#47]
@sarahcd I noticed that the following (new) terms have labels that are written with hyphen:

- `deploy-off measurements`: http://vocab.nerc.ac.uk/collection/MVB/current/MVB000354/
- `deploy-off sampling`: http://vocab.nerc.ac.uk/collection/MVB/current/MVB000355/
- `deploy-on measurements`: http://vocab.nerc.ac.uk/collection/MVB/current/MVB000356/
- `deploy-on sampling`: http://vocab.nerc.ac.uk/collection/MVB/current/MVB000357/
- `GSM MCC-MNC`: http://vocab.nerc.ac.uk/collection/MVB/current/MVB000125/
- `animal birth-hatch latitude`: http://vocab.nerc.ac.uk/collection/MVB/current/MVB000338/
- `animal birth-hatch longitude`: http://vocab.nerc.ac.uk/collection/MVB/current/MVB000339/
- `study-specific measurement`: http://vocab.nerc.ac.uk/collection/MVB/current/MVB000178/

This in contrast with previous terms:

- `deploy off timestamp`, etc.: http://vocab.nerc.ac.uk/collection/MVB/current/MVB000077/
- `deploy on timestamp`, etc: http://vocab.nerc.ac.uk/collection/MVB/current/MVB000081/
- `animal death comments`, etc.: http://vocab.nerc.ac.uk/collection/MVB/current/MVB000013/
- In fact, none of the other terms are written with hyphen.

The extra hyphen makes it annoying to find the term, since we ignore all `-`, `_`,  and `.` to look up a term. Is it possible to change the labels to make them consistent?

**Comment by peterdesmet** [comment]
Note also that some definitions in other terms (e.g. [capture handling time](http://vocab.nerc.ac.uk/collection/MVB/current/MVB000349/)) refer to the terms with hypnen, while they are written without:

> The time elapsed between capture and release of the animal for the purpose of attaching the tag. Can also be calculated as the difference between 'deploy-on timestamp' and 'capture timestamp'. Example: '552'; Units: seconds; Entity described: deployment

**Comment by peterdesmet** [comment]
This issue is a blocker for publishing our data :-/

**Comment by peterdesmet** [comment]
Hi @sarahcd, any idea when this would be resolved in the vocabulary? Even adding the hyphen-less names as `alternative label` would resolve this, but better is to have them hyphen-less as canonical names.

**Comment by sarahcd** [comment]
Sorry for the trouble @peterdesmet — I noticed this also and have the changes prepared for the next update—removing hyphens from the names. I plan to do this in the next month.

**Comment by peterdesmet** [comment]
You expect an update in August? Great! I'll postpone publication until then, can you keep me posted?

**Comment by sarahcd** [comment]
Fixed at http://vocab.nerc.ac.uk/collection/MVB with an update that went live last night. Sorry for the wait!

**Comment by peterdesmet** [comment]
Names confirmed fixed in latest update. @sarahcd note that [some terms still refer to terms with hyphen in their description](https://github.com/inbo/movepub/issues/47#issuecomment-1612653487), maybe good to put on your radar for the next update. Closing issue.
