### ISSUE TITLE
Unrecognized character in definition for `GSM signal strength`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#48]
See http://vocab.nerc.ac.uk/collection/MVB/current/MVB000126/:

> An integer proportional to the GSM signal strength measured by the tag. Valid values are 0�31, or 99 for unknown or undetectable. Higher values indicate better signal strength. Example: '39'; Units: arbitrary strength units (asu); Entity described: event

**Comment by sarahcd** [comment]
That is a problem reading an N-dash (should be 0–31). In the next update this will be replaced with a hyphen (0-31) to avoid problems.

**Comment by peterdesmet** [comment]
Confirmed fixed in latest update.
