### ISSUE TITLE
Provide copy of `read_package()` and `write_package()` from frictionless

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#54]
Currently, users of movepub have to load the frictionless package to work with datasets (see https://inbo.github.io/movepub/articles/movepub.html).

It might be useful if the functions `read_package()` and `write_package()` are copied from frictionless and exposed through movepub, cf. how `readr::problems()` is exposed in camtraptor. That also avoids the name clash warning between `frictionless::add_resource()` and `movepub::add_resource()`.

**Comment by sannegovaert** [comment]
I see 2 ways to do this:
- A new function in movepub, just as [`check_reading_issues()`](https://github.com/inbo/camtraptor/blob/f62b937766435f2e729c21443cbe3189f6765090/R/zzz.R#L111) in camptraptor.
- As a reexport from frictionless, just as the [reexports from camtrapdp](https://github.com/inbo/camtraptor/blob/version-1.0/R/camtrapdp-reexports.R) in camtraptor.

**Comment by peterdesmet** [comment]
I agree, option 2 is the most elegant. If this is done, please also update:

- [ ] Vignette
- [ ] README
- [ ] Examples
- [ ] Tests?

**Comment by sannegovaert** [comment]
What needs to be updated in README?
And does something need to happen with the `add_resource()` function?
