### ISSUE TITLE
Split `write_dwc()` into `write_dwc()` and `write_eml()`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#57]
Ideally, `write_dwc()` can be used in an operational pipeline and doesn't generate errors. Currently, that is not the case, since it requires e.g. a rightsholder, contact person, etc. Does properties are actually required for the EML part, not the Darwin Core transformations.

- [ ] Update https://github.com/tdwg/dwc-for-biologging/wiki/Movebank-GPS-data

**Comment by sangovae** [comment]
Package `EML` also has a `write_eml()` function. This could be confusing?

**Comment by peterdesmet** [comment]
I think that's ok

**Comment by sangovae** [comment]
fixed in #69
