### ISSUE TITLE
Make clickable aphia_id in message

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#58]
`write_dwc()` currently returns the found aphia_ids:

``` r
library(frictionless)
library(movepub)
p <- read_package("https://zenodo.org/records/10055071/files/datapackage.json")
#> Please make sure you have the right to access data from this Data Package for your intended use.
#> Follow applicable norms or requirements to credit the dataset and its authors.
#> For more information, see https://doi.org/10.5281/zenodo.10055071
dwc <- write_dwc(p, directory = ".")
#> 
#> ── Reading data ──
#> 
#> ℹ Taxa found in reference data and their WoRMS AphiaID:
#> Circus cyaneus: 159372
#> Asio flammeus: 212685
#> Circus pygargus: 1037307
#> Circus aeruginosus: 558541
#> Buteo buteo: 558534
#> 
#> ── Transforming data to Darwin Core ──
#> 
#> ── Writing files ──
#> 
#> • 'eml_path'
#> • 'dwc_occurrence_path'
```

<sup>Created on 2023-12-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

It would be nice if those aphia_ids were clickable links, which can be done with:

``` r
library(cli)
library(movepub)
taxon <- get_aphia_id("Circus cyaneus")
cli::cli_li("{taxon[['name']]}: {.href [{taxon['aphia_id']}]({taxon['aphia_url']})}.")
#> • Circus cyaneus: 159372
#> (<https://www.marinespecies.org/aphia.php?p=taxdetails&id=159372>).
```

<sup>Created on 2023-12-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

But it takes some handling of `NA` and multiple values that I haven't been able to debug.

**Comment by sannegovaert** [comment]
I have a solution for the NA's, but now there is an unwanted message from cli. No clue what it means and how to get rid of it.
``` r
library(cli)
library(movepub)
library(purrr)
names <- c("Mola mola", "not a name")

print_clickable_aphia_id <- function(name) {
  taxa <- get_aphia_id(names)
  record <- taxa %>% 
    dplyr::filter(.data$name == {{ name }})
  if (is.na(record$aphia_id)) {
    cli::cli_li("{name}: NA")
  } else {
    cli::cli_li("{name}: {.href [{record['aphia_id']}]({record['aphia_url']})}")
  }
}

purrr::map(names, print_clickable_aphia_id)
#> • Mola mola: 127405
#> (<https://www.marinespecies.org/aphia.php?p=taxdetails&id=127405>)
#> • not a name: NA
#> [[1]]
#> [1] "cli-158280-1"
#> 
#> [[2]]
#> [1] "cli-158280-11"
```

<sup>Created on 2024-08-07 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by peterdesmet** [comment]
Hmm, I can't debug this. I would update the `get_aphia_id()` to add a cli_based column, see my #83

I also notice that (only) providing a non-existing name to `get_aphia_id("not_a_name")` results in an error, because this line expects a non-empty dataframe:

https://github.com/inbo/movepub/blob/67a404cd36ea2412bb4a6aee6e81a5360d2ef6a8/R/get_aphia_id.R#L20

@sannegovaert maybe you can continue #83 to resolve this?
