### ISSUE TITLE
Create helper functions for `write_dwc()`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#66]
`write_dwc()` is currently too long and is better split in helper functions. This will also help to call certain functions for certain data (gps vs bird ring etc.)

## Still in write_dwc()

- [x] Read resources as dataframes (we don't want to do this multiple times)
- [x] Get taxa from ref (we don't want to do this multiple times)
- [x] Binding the occurrence df from the helper functions
- [x] Adding the DATASET-LEVEL terms

## dwc_occurrence_ref()

- [x] File: `dwc_occurrence_ref.R`
- [x] Document function, but use `@noRd`
- [x] Parameters: ref (dataframe), taxa (dataframe)
- [x] Applies `expand_col()` in function, but only with the columns that are used in the mapping
- [x] Applies dplyr mapping
- [x] Returns df

## dwc_occurrence_gps()

- [x] File: `dwc_occurrence_gps.R`
- [x] Document function, but use `@noRd`
- [x] Parameters: ref (dataframe), taxa (dataframe), gps (dataframe)
- [x] Applies `expand_col()` in function, but only with the columns that are used in the mapping
- [x] Applies dplyr mapping
- [x] Returns df

**Comment by sangovae** [comment]
fixed in #69
