### ISSUE TITLE
DwC mapping of Movebank

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#7]
## Record-level

See #12

## Deployment

- [x] basisOfRecord
- [x] occurrenceID: **don't use deploymentID (not always assigned), use same value as `dwc:eventID`**
- [x] individualCount: add? **no**
- [x] sex: unknown -> [undetermined](https://rs.gbif.org/vocabulary/gbif/sex.xml) **left as unknown**
- [x] lifeStage: map as is? **yes**
- [x] occurrenceStatus
- [x] organismID
- [x] organismName
- [x] eventID: use `ref."animal-id" ||  '_' || ref."tag-id"` (different order, not a hyphen)
- [x] samplingProtocol: `tag deployment`? **use `tag attachment`**
- [x] eventDate
- [x] eventRemarks: yes, use this since it will show on [GBIF](https://www.gbif-uat.org/dataset/0ef15f32-b41d-4274-ae96-eb5d0059fee6/event/5624-l922112). Also include more information:

```
ref."tag-manufacturer-name" + ref."tag-model" "tag attached to "
CASE
 WHEN ref."manipulation-type" = 'none' THEN 'free-ranging animal'
 WHEN ref."manipulation-type" != 'none' THEN 'manipulated animal (see original dataset)' -- Or exclude these animals from GBIF. 
END
"by" ref."attachment-type"
```

- [x] minimumDistanceAboveSurfaceInMeters: NULL
- [x] decimalLatitude: round to 5? **keep as is**
- [x] decimalLongitude: round to 5? **keep as is**
- [x] geodeticDatum **Make conditional on decimalLatitude**
- [x] coordinateUncertaintyInMeters: 30? **Use 1000, make conditional on decimalLatitude**
- [x] taxonID: available? **Yes, in database (ITIS TSN), but would have to be retrieved through https://www.movebank.org/movebank/service/direct-read?entity_type=taxon&canonical_name=Phoebastria%20irrorata). However, since scientificNames are already standardized, it's not really worth it**
- [x] scientificName
- [x] kingdom: set to `Animalia` **yes**
- [x] rank: available? **almost always species, but subspecies could happen too**

## GPS

- [x] basisOfRecord
- [x] dataGeneralizations: `Example `subsampled by hour: first of x records`? **ok**
- [x] occurrenceID: prefix with something? `movebank:00000` **use identifier as is**
- [x] sex: NULL **or map? Now mapped**
- [x] lifeStage: NULL, see #11
- [x] occurrenceStatus
- [x] organismID
- [x] organismName
- [x] eventID: **update**
- [x] samplingProtocol: gps."sensor-type"? **yes**
- [x] eventDate
- [x] eventRemarks: NULL
- [x] minimumDistanceAboveSurfaceInMeters: height-above-msl
- [x] decimalLatitude: round to 5? **keep as is**
- [x] decimalLongitude: round to 5? **keep as is**
- [x] geodeticDatum
- [x] coordinateUncertaintyInMeters
- [x] scientificName
- [x] kingdom: set to `Animalia` **yes**

**Comment by sarahcd** [comment]
Noting other things to cover:
- [ ] deployment-id as occurrenceID

**Comment by peterdesmet** [comment]
Do you want an example dataset with the current output? Might be easier to inspect?

**Comment by sarahcd** [comment]
Sure! I have the one you posted on GBIF.

**Comment by peterdesmet** [comment]
Ah yes, that is perfect. DwC data is at https://ipt.gbif.org/archive.do?r=o_westerschelde

**Comment by peterdesmet** [comment]
For dataset title, @timrobertson100 suggests:

```
Title: <name> (subsampled representation)
Description:
This dataset represents a subsampled view of the original dataset available on <doi> in MoveBank.
The original dataset was subsampled by …… The original dataset description follows.
<original description>
```

**Comment by sarahcd** [comment]
Sounds fine to me!

**Comment by peterdesmet** [comment]
@sarahcd `sex` is now populated for the GPS records. Should we set `lifeStage` for those records to `adult` if the animal was an adult when captured?

**Comment by sarahcd** [comment]
> @sarahcd is it possible for the coordinates of the gps records to be NULL or will those be marked as `visible=false`?

Important point, thanks for catching this! It is possible to have null (empty) coordinate fields that are not marked as outliers. (Sometimes there are other sensor measurements in the record, e.g., battery charge, that the user might want to retain in some contexts, so we don't automatically flag these.) Ideally this would be a preprocessing step, removing these before subsampling records.
