### ISSUE TITLE
Allow to create Darwin Core Archive for non-published dataset

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#72]
- [x] Don't call `datacite_to_eml()`
- [x] Allow to provide `dataset_id = package$id`
- [x] Allow to provide `dataset_name = package$title`
- [x] Allow to provide rights_holder
- [x] Allow to provide `license`
- [x] Indicate this in the documentation, cf. https://github.com/inbo/camtrapdp/blob/f48d89eef6abc07e44bbd164aab05f772590a672/R/write_dwc.R#L36-L45

**Comment by sarahcd** [comment]
@peterdesmet what is the use case? Let me know if you want me to check code or examples for this.

**Comment by peterdesmet** [comment]
`write_dwc()` currently demands a DOI to exist, but only in order to populate `datasetID`. I think that's too strict of a condition. I've noticed people also use the `write_dwc()` function to transform Movebank data to Darwin Core (e.g. to downsample), without the necessity of having it published, see e.g. http://doi.org/10.1111/ecog.07246

**Comment by sarahcd** [comment]
I agree. In terms of Movebank the source study/url (like you use in the metadata for your Zenodo data pubs) is an easy place to start. I'd just want to be sure that we guide the user through appropriate use, e.g., they might translate and resample data for various uses, but should not then publish it on GBIF if it is not 'their' data (even if it is CC0). This could get a little fuzzy.

**Comment by peterdesmet** [comment]
@sannegovaert, in the NEWS.md I already [assumed this to be resolved](https://github.com/inbo/movepub/blob/8edad4782ee6ba6480f96c5e44cec687a694f8ca/NEWS.md?plain=1#L3), so it would be good to tackle this as part of the upcoming 0.4.0. 😄

**Comment by peterdesmet** [comment]
See https://github.com/inbo/camtrapdp/blob/70dfd77b19ce6997b66894bcd52bd7d86bd0a4fc/R/write_dwc.R#L55-L70 for inspiration

**Comment by sannegovaert** [comment]
The example paclage o_assen does not have a title or a license. What should be adapated when implementing this feature, o_assen or the tests ?

**Comment by peterdesmet** [comment]
Let's update `o_assen.rda`. Please update https://github.com/inbo/movepub/blob/67a404cd36ea2412bb4a6aee6e81a5360d2ef6a8/R/data.R#L15-L19 to:

```R
# The data in o_assen was created with the code below
o_assen <-
  frictionless::read_package("https://zenodo.org/records/10053903/files/datapackage.json") %>%
  frictionless::remove_resource("acceleration")
o_assen$title <- "O_ASSEN - Eurasian oystercatchers (Haematopus ostralegus, Haematopodidae) breeding in Assen (the Netherlands)"
o_assen$licenses[[1]]$path <- "https://creativecommons.org/publicdomain/zero/1.0/"
usethis::use_data(o_assen)
```

Note: this will slightly change the license URL in the snapshot in the test. The snapshot can be updated.
