### ISSUE TITLE
Update DwC section of Getting Started guide

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#79]
The [Transform a Movebank dataset to Darwin Core](https://inbo.github.io/movepub/articles/movepub.html#dwc) of the Getting Started guide still assumes that `write_dwc()` writes both data and `eml.xml`, while this has now been split over two functions. This should be updated.

- [ ] Show functionality of `write_dwc()`
- [ ] Show functionality of `write_eml()`

This should be fixed before we release version 0.4.0

@sannegovaert The source for this guide is in https://github.com/inbo/movepub/blob/main/vignettes/movepub.Rmd.orig. It can be build to a Rmd by running https://github.com/inbo/movepub/blob/main/vignettes/precompile.R

**Comment by sannegovaert** [comment]
This has been updated in PR #75 .
Or do you mean something else?

**Comment by sannegovaert** [comment]
Most of the updates were done in PR #75 , but some more updates are needed.
