### ISSUE TITLE
Vignette seems to use frictionless and EML rather than movepub

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#86]
If I don't prepend `movepub::add_resource()` and `movepub::write_eml()`, the vignette seems to default to frictionless and EML for those functions, even though those functions are not loaded. I don't understand why.

@sannegovaert can you debug? For `add_resource()` it might be worth to rename to `add_movepub_resource()` to be explicit?

**Comment by sannegovaert** [comment]
I don't have this problem. Seems to be something local?

**Comment by peterdesmet** [comment]
Indeed, clearing my session entirely resolved the issue. 🤷
